"""Generated data reports (`eval/reports/`). Numbers here are never edited by hand.

- `parser_fidelity`: every leaf value in every source DDR is accounted for by the parser.
- `data_qc`: per-wellbore coverage of the canonical model after loading.

Output is deterministic (no timestamps) so a diff shows only real changes.
"""

import json
import statistics
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from sqlalchemy import case, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from drillsage.core.basin_packs import load_basin_pack
from drillsage.core.config import get_settings
from drillsage.db import models as m
from drillsage.domain.trajectory import Trajectory, TrajectoryStation, TvdSource
from drillsage.ingest.pipeline import PARSER_VERSION, ddr_paths
from drillsage.ingest.witsml_ddr import parse_ddr
from drillsage.ingest.xml_safe import parse_xml
from drillsage.ingest.xmlmap import model_value_counts, source_leaf_counts


@dataclass(frozen=True, slots=True)
class FidelityResult:
    files: int
    reports: int
    source_values: int
    mapped_values: int
    unmapped_values: int
    null_sentinels_source: int
    null_sentinels_parsed: int
    values_expected: int
    values_parsed: int
    coverage_pct: float
    mismatched_paths: list[str]
    unmapped_paths: dict[str, int]
    sections: dict[str, int]


def parser_fidelity(data_dir: Path) -> FidelityResult:
    source: Counter[str] = Counter()
    nulls: Counter[str] = Counter()
    mapped: Counter[str] = Counter()
    unmapped: Counter[str] = Counter()
    parsed_nulls: Counter[str] = Counter()
    parsed_values: Counter[str] = Counter()
    paths = ddr_paths(data_dir)
    report_count = 0
    for path in paths:
        data = path.read_bytes()
        parsed = parse_ddr(data)
        report_count += len(parsed.document.reports)
        values, null_values = source_leaf_counts(parse_xml(data))
        source += values
        nulls += null_values
        mapped += parsed.report.mapped
        unmapped += parsed.report.unmapped
        parsed_nulls += parsed.report.nulls
        parsed_values += model_value_counts(parsed.document, "/drillReports")

    mismatched = sorted(
        p
        for p in source
        if mapped[p] != source[p]
        or parsed_values[p] != source[p] - nulls[p]
        or parsed_nulls[p] != nulls[p]
    )
    total = sum(source.values())
    sections: Counter[str] = Counter()
    for p, n in source.items():
        parts = p.split("/")
        sections[parts[3] if len(parts) > 3 and parts[2] == "drillReport" else parts[2]] += n  # noqa: PLR2004
    ok = total - sum(source[p] for p in mismatched)
    return FidelityResult(
        files=len(paths),
        reports=report_count,
        source_values=total,
        mapped_values=sum(mapped.values()),
        unmapped_values=sum(unmapped.values()),
        null_sentinels_source=sum(nulls.values()),
        null_sentinels_parsed=sum(parsed_nulls.values()),
        values_expected=total - sum(nulls.values()),
        values_parsed=sum(parsed_values.values()),
        coverage_pct=round(100.0 * ok / total, 3) if total else 0.0,
        mismatched_paths=mismatched,
        unmapped_paths=dict(sorted(unmapped.items())),
        sections=dict(sorted(sections.items(), key=lambda kv: (-kv[1], kv[0]))),
    )


def write_parser_fidelity(data_dir: Path, out_dir: Path) -> FidelityResult:
    result = parser_fidelity(data_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {"parser_version": PARSER_VERSION, **asdict(result)}
    (out_dir / "parser_fidelity.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    rows = "\n".join(f"| `{name}` | {count:,} |" for name, count in result.sections.items())
    nulls_parsed = f"{result.null_sentinels_parsed:,} read as null"
    status = "PASS" if result.coverage_pct == 100.0 else "FAIL"  # noqa: PLR2004
    md = f"""# Parser fidelity: WITSML daily drilling reports

Generated by `make eval-parser` (`drillsage-data fidelity`). Do not edit by hand.

**Result: {status}, {result.coverage_pct}% of source values accounted for** (target 100%).

| Check | Source XML | Parser |
|---|---:|---:|
| Files | {result.files:,} | {result.files:,} parsed |
| Daily reports | | {result.reports:,} |
| Leaf values (non-empty elements) | {result.source_values:,} | {result.mapped_values:,} mapped |
| Unmapped leaf values | | {result.unmapped_values:,} |
| Null sentinels (`-999.99`) | {result.null_sentinels_source:,} | {nulls_parsed} |
| Real values kept after null handling | {result.values_expected:,} | {result.values_parsed:,} |
| Paths with any mismatch | | {len(result.mismatched_paths)} |

How it is measured: an independent walk of each XML tree counts every non-empty leaf element
by path. The parser reports which paths it mapped, which it did not recognise, and which were
null sentinels; the parsed model is then walked again to count the values it actually holds.
A path passes only when all three counts agree.

Parser version `{PARSER_VERSION}`. Every quantity is converted from its `uom` attribute to
DrillSage canonical units; unknown units fail the parse instead of being guessed.

## Leaf values by section

| Section | Values |
|---|---:|
{rows}
"""
    (out_dir / "parser_fidelity.md").write_text(md, encoding="utf-8")
    return result


MAX_SURVEY_GAP_M = 50.0
"""Beyond this gap between the last survey and TD, a TVD comparison would test extrapolation."""


def _trajectory(rows: list[m.TrajectoryStation]) -> Trajectory:
    return Trajectory(
        [
            TrajectoryStation(
                md_m=r.md_m,
                incl_deg=r.incl_deg,
                azi_deg=r.azi_deg,
                tvd_m=r.tvd_m,
                north_m=r.north_m,
                east_m=r.east_m,
                dls_deg_per_30m=r.dls_deg_per_30m,
                tvd_mincurv_m=r.tvd_mincurv_m,
                tvd_reported_m=r.tvd_reported_m,
                tvd_source=TvdSource(r.tvd_source),
                reported_rejected=r.reported_tvd_rejected,
                inherited=r.inherited,
            )
            for r in rows
        ]
    )


def _round(value: float | None, digits: int = 1) -> float | None:
    return None if value is None else round(value, digits)


async def collect_data_qc(session: AsyncSession) -> dict[str, Any]:
    """Per-wellbore coverage of the canonical model; the evidence for the Phase 1 exit gate."""
    wb = m.Wellbore
    parent = m.Wellbore.__table__.alias("parent")
    report_counts: dict[int, int] = dict(
        (
            await session.execute(
                select(m.DailyReport.wellbore_id, func.count()).group_by(m.DailyReport.wellbore_id)
            )
        )
        .tuples()
        .all()
    )
    activity_counts: dict[int, int] = dict(
        (
            await session.execute(
                select(m.Activity.wellbore_id, func.count()).group_by(m.Activity.wellbore_id)
            )
        )
        .tuples()
        .all()
    )
    stations: dict[int, list[m.TrajectoryStation]] = defaultdict(list)
    for station in (
        await session.execute(
            select(m.TrajectoryStation).order_by(
                m.TrajectoryStation.wellbore_id, m.TrajectoryStation.seq
            )
        )
    ).scalars():
        stations[station.wellbore_id].append(station)
    tops: dict[int, Counter[str]] = defaultdict(Counter)
    origin = case(
        (m.FormationTop.inherited_from_id.is_not(None), "inherited"), else_=m.FormationTop.source
    )
    for wid, source, n in (
        await session.execute(
            select(m.FormationTop.wellbore_id, origin, func.count()).group_by(
                m.FormationTop.wellbore_id, origin
            )
        )
    ).tuples():
        tops[wid][source] = n

    rows = (
        await session.execute(
            select(wb, m.Well, parent.c.name)
            .join(m.Well, m.Well.id == wb.well_id)
            .outerjoin(parent, parent.c.id == wb.parent_id)
            .order_by(wb.name)
        )
    ).tuples()
    wellbores: list[dict[str, Any]] = []
    for w, well, parent_name in rows:
        own = stations.get(w.id, [])
        sources = Counter(s.tvd_source for s in own)
        tvd_check = survey_gap = None
        if own and w.total_depth_md_m is not None and w.final_tvd_m is not None:
            survey_gap = max(0.0, w.total_depth_md_m - max(s.md_m for s in own))
            if survey_gap <= MAX_SURVEY_GAP_M:
                tvd_check = _trajectory(own).tvd_at_md(w.total_depth_md_m) - w.final_tvd_m
        wellbores.append(
            {
                "wellbore": w.name,
                "kind": w.kind,
                "parent": parent_name,
                "kickoff_md_m": w.kickoff_md_m,
                "reports": report_counts.get(w.id, 0),
                "activities": activity_counts.get(w.id, 0),
                "lat_deg": round(well.surface_lat_deg, 6),
                "lon_deg": round(well.surface_lon_deg, 6),
                "kb_elevation_m": w.kb_elevation_m,
                "trajectory_stations": len(own),
                "max_md_m": _round(max((s.md_m for s in own), default=None)),
                "max_tvd_m": _round(max((s.tvd_m for s in own), default=None)),
                "tvd_reported": sources[TvdSource.REPORTED.value],
                "tvd_adjusted": sources[TvdSource.ADJUSTED.value],
                "tvd_min_curvature": sources[TvdSource.MINIMUM_CURVATURE.value],
                "reported_tvd_rejected": sum(1 for s in own if s.reported_tvd_rejected),
                "sodir_td_md_m": w.total_depth_md_m,
                "sodir_final_tvd_m": w.final_tvd_m,
                "tvd_error_at_td_m": _round(tvd_check),
                "surveys_end_short_of_td_m": _round(survey_gap),
                "formation_tops_sodir": tops[w.id]["sodir"],
                "formation_tops_ddr": tops[w.id]["ddr"],
                "formation_tops_inherited": tops[w.id]["inherited"],
                "formation_tops_correlated": tops[w.id]["correlated"],
            }
        )

    pack = load_basin_pack(get_settings().basin_pack)
    picks = (await session.execute(select(m.StratPick.description))).scalars().all()
    unresolved = Counter(p for p in picks if p and pack.resolve(p) is None)

    checked = [w for w in wellbores if w["tvd_error_at_td_m"] is not None]
    gate = {
        "wellbores": len(wellbores),
        "with_coordinates": sum(1 for w in wellbores if w["lat_deg"] is not None),
        "with_trajectory": sum(1 for w in wellbores if w["trajectory_stations"] > 1),
        "with_formation_tops": sum(
            1
            for w in wellbores
            if w["formation_tops_sodir"]
            + w["formation_tops_ddr"]
            + w["formation_tops_inherited"]
            + w["formation_tops_correlated"]
            > 0
        ),
        "with_correlated_tops_only": [
            w["wellbore"] for w in wellbores if w["formation_tops_correlated"] > 0
        ],
        "tvd_checked_against_sodir": len(checked),
        "surveys_short_of_sodir_td": [
            w["wellbore"]
            for w in wellbores
            if w["surveys_end_short_of_td_m"] is not None
            and w["surveys_end_short_of_td_m"] > MAX_SURVEY_GAP_M
        ],
        "tvd_abs_error_at_td_max_m": max(
            (abs(w["tvd_error_at_td_m"]) for w in checked), default=None
        ),
        "tvd_abs_error_at_td_median_m": _round(
            statistics.median(abs(w["tvd_error_at_td_m"]) for w in checked) if checked else None
        ),
    }
    return {
        "basin_pack": pack.key,
        "gate": gate,
        "wellbores": wellbores,
        "unresolved_formation_picks": dict(sorted(unresolved.items())),
    }


def write_data_qc(payload: dict[str, Any], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "data_qc.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (out_dir / "data_qc.md").write_text(_data_qc_markdown(payload), encoding="utf-8")


def _cell(value: object) -> str:
    if value is None:
        return ""
    return f"{value:,}" if isinstance(value, int) else str(value)


_QC_COLUMNS = (
    ("wellbore", "Wellbore"),
    ("kind", "Kind"),
    ("parent", "Parent"),
    ("kickoff_md_m", "Kick-off MD (m)"),
    ("reports", "Reports"),
    ("activities", "Activities"),
    ("trajectory_stations", "Stations"),
    ("max_md_m", "Max MD (m)"),
    ("max_tvd_m", "Max TVD (m)"),
    ("tvd_reported", "TVD reported"),
    ("tvd_adjusted", "TVD adjusted"),
    ("reported_tvd_rejected", "Reported TVD rejected"),
    ("tvd_error_at_td_m", "TVD error at TD vs Sodir (m)"),
    ("formation_tops_sodir", "Sodir tops"),
    ("formation_tops_ddr", "DDR tops"),
    ("formation_tops_inherited", "Inherited tops"),
    ("formation_tops_correlated", "Correlated tops"),
)


def _data_qc_markdown(payload: dict[str, Any]) -> str:
    pack_key: str = payload["basin_pack"]
    gate: dict[str, Any] = payload["gate"]
    wellbores: list[dict[str, Any]] = payload["wellbores"]
    unresolved: dict[str, int] = payload["unresolved_formation_picks"]
    correlated_only = ", ".join(gate["with_correlated_tops_only"]) or "none"
    short_of_td = ", ".join(gate["surveys_short_of_sodir_td"]) or "none"
    error_median = _cell(gate["tvd_abs_error_at_td_median_m"])
    error_max = _cell(_round(gate["tvd_abs_error_at_td_max_m"]))
    header = "| " + " | ".join(title for _, title in _QC_COLUMNS) + " |"
    align = "|" + "|".join("---" if i < 3 else "---:" for i in range(len(_QC_COLUMNS))) + "|"  # noqa: PLR2004
    body = "\n".join(
        "| " + " | ".join(_cell(w[key]) for key, _ in _QC_COLUMNS) + " |" for w in wellbores
    )
    unresolved_rows = (
        "\n".join(f"| {name} | {n} |" for name, n in sorted(unresolved.items())) or "| (none) | |"
    )
    return f"""# Data QC: canonical model after `make data`

Generated by `drillsage-data qc`. Do not edit by hand. Basin pack: `{pack_key}`.

| Gate check | Result |
|---|---:|
| Wellbores | {gate["wellbores"]} |
| With surface coordinates (WGS84) | {gate["with_coordinates"]} |
| With a trajectory | {gate["with_trajectory"]} |
| With formation tops | {gate["with_formation_tops"]} |
| Of which field-correlated only (no picks in the wellbore) | {correlated_only} |
| TVD at TD checked against Sodir final TVD | {gate["tvd_checked_against_sodir"]} wellbores |
| Median / max absolute TVD error at TD | {error_median} m / {error_max} m |
| Surveys end more than {MAX_SURVEY_GAP_M:.0f} m short of Sodir TD (not checked) | {short_of_td} |

**How TVD is built.** Daily reports carry both inclination/azimuth and the operator's reported
TVD, and each has errors: isolated typing errors in reported TVD, and runs of wrong
inclinations. DrillSage computes minimum curvature, rejects reported TVDs that spike away from
neighbours that agree with each other, follows the accepted reported TVDs, and shifts the
minimum-curvature shape between them. *TVD reported* / *adjusted* count stations of each kind;
*rejected* counts reported values identified as typing errors.

**Independent check.** The Norwegian Offshore Directorate (Sodir) publishes each wellbore's
total depth and final TVD. The error column interpolates DrillSage's trajectory at Sodir's
TD and subtracts Sodir's final TVD. It is blank for wellbores that were later technically
sidetracked, because Sodir's figures then describe the sidetrack's hole, and for wellbores
whose daily reports stop surveying well before TD (the comparison would only test a
straight-line extrapolation).

{header}
{align}
{body}

**Formation tops.** In priority order: Sodir's interpreted lithostratigraphy, the wellsite
geologist's picks in the daily reports, tops inherited from the parent hole above a sidetrack's
kick-off, and, for a wellbore with no picks at all, the unit's median TVDSS across the field's
wells (supported by at least 3 wells). Correlated tops are lower confidence and labelled so
wherever they are shown.

## Formation picks not in the basin pack

These names appear in daily-report `stratInfo` but are not units of the `{pack_key}` pack
(most are Norwegian Sea formations that do not occur in block 15/9). They stay in
`strat_picks` but are never used for formation alignment.

| Reported name | Picks |
|---|---:|
{unresolved_rows}
"""
